version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - 3050:80

  redis-server:
    restart: always
    image: "redis"

  api:
    restart: always
    build: ./api
    depends_on:
      - redis-server

  client:
    restart: always
    build: ./client
    environment:
      - PORT=3000
    depends_on:
      - api
