version: '3'

services:

  redis-server:
    restart: always
    image: "redis"

  api:
    restart: always
    build: ./api
    ports:
      - "8007:8007"

  client:
    restart: always
    build: ./client
    environment:
      - "PORT=3001"
    ports:
      - "3001:3001"
    depends_on:
      - api
