version: '3'

services:

  redis-server:
    image: "redis"

  api:
    build: ./api
    ports: 
      - "8007:8007"

  client-a:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app/client
      - /app/client/node_modules